apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: guacamole
        image: guacamole/guacamole:latest
        ports:
        - containerPort: 8080
        env:
        - name: EXTENSIONS
          value: "openid"
        - name: GUACD_HOSTNAME
          value: "guacd-service"
        - name: GUACD_PORT
          value: "4822"
        - name: POSTGRESQL_HOSTNAME
          value: "postgres-service"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres-db
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres-password
        - name: OPENID_AUTHORIZATION_ENDPOINT
          value: "https://accounts.google.com/o/oauth2/v2/auth"
        - name: OPENID_JWKS_ENDPOINT
          value: "https://www.googleapis.com/oauth2/v3/certs"
        - name: OPENID_ISSUER
          value: "https://accounts.google.com"
        - name: OPENID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: guacamole-oidc-secret
              key: client-id
        - name: OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: guacamole-oidc-secret
              key: client-secret
        - name: OPENID_REDIRECT_URI
          value: "https://guacamole.dagnelli.net/guacamole/"
        - name: OPENID_USERNAME_CLAIM_TYPE
          value: "email"
        - name: OPENID_SCOPE
          value: "openid email profile"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /guacamole
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /guacamole
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
